name: Build docker

on:
  push:
    paths: 
      - "scripts/dockers/**"

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        database: ["sqlite", "mariadb", "mysql", "postgresql"]
    steps:
    - uses: actions/checkout@v3
    - name: "Check file existence"
      id: check_files
      uses: andstor/file-existence-action@v2
      with:
        files: "scripts/dockers/${{matrix.database}}/Dockerfile"
    - name: Build the Docker image for each database
      if: steps.check_files.outputs.files_exists == 'true'
      run: docker build . --file Dockerfile 
      working-directory: "scripts/dockers/${{matrix.database}}"
